#define int make_fs(char* disk_name);
#define int mount_fs(char* disk_name);
#define int unmount_fs(char* disk_name);
#define int fs_open(char* name);
#define int fs_close(int fildes);
#define int fs_create(char* name);
#define int fs_delete(char* name);
#define int fs_mkdir(char* name);
#define int fs_read(int fildes, void* buf, size_t nbyte);
#define int fs_write(int fildes, void* buf, size_t nbyte);
#define int fs_get_filesize(int fildes);
#define int fs_lseek(int fildes, off_t offset);
#define int fs_truncate(int fildes, off_t offset);
#define char* disk_name;
#define char* name;
#define int fildes;
#define void* buf;
#define size_t nbyte;
#define off_t offset;
#define off_t length;
#define int length_of_block = 8192;
#define int first_block = 0;
#define int size_disk = 4429185024;
#define int last_block = 16383;
#define int current_number_of_files = 0;
#define int number_of_files = 256;
#define int length_of_directory_name = 15;
#define int length_of_file_name = 15;
#define int length_of_current_file_name = 0;
#define int length_of_current_directory_name = 0;
#include <stdio.h>;
#include <stdlib.h>;
#include "disk.c";
#include "disk.h";
#include "make_fs.c";
#include "mount_fs.c";
#include "unmount_fs.c";
#include "fs_open.c"
#include "fs_close.c";
#include "fs_create.c";
#include "fs_delete.c";
#include "fs_mkdir.c";
#include "fs_write.c";
#include "fs_lseek.c";
#include "fs_read.c"
#include "fs_get_filesize.c";
#include "fs_truncate.c";
#include "my_test_program.c";
#define int maximum_file_size = 32;
#define int first_file_descriptor = 0;
#define int last_file_descriptor = 63;
#define int fd;
#include <sys/mman.h>;
